language: node_js
node_js:
- 8
cache: yarn
script:
- npm run lint
- npm run build
addons:
  ssh_known_hosts: szp.io
before_install:
- export TZ=Asia/Shanghai
- openssl aes-256-cbc -K $encrypted_93d5d24fc098_key -iv $encrypted_93d5d24fc098_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/site/.vuepress/dist/ sun@szp.io:/srv/http/blog
  on:
    branch: master
